- name: install pip libs
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL 
  - cryptography

- name: mysql - server
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ r_pw }}"
    login_host: mysql.katta.blog
  register: mysql_info
  ignore_errors: true

- name: print the output
  ansible.builtin.debug:
    msg: "Mysql info: {{mysql_info}}"

- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ r_pw }}"
  when: mysql_info.failed is true