- name: remove existing directory
  ansible.builtin.file:
    path: "{{ app_location }}" # for backend /app for frontend //usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}" # for backend /app for frontend //usr/share/nginx/html
    state: directory

- name: download the file
  ansible.builtin.get_url:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ cmp }}-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes